### PR TITLE
10% chance to respond with that stupid xkcd

### PR DESCRIPTION
**Pull request by stevendiaz**

### CODE REVIEW

**Comment by arrdem** [comment]
FAN IS BEST FEATURE GO AWAY

**Comment by ThomasGaubert** [comment]
:rip:

**Comment by aaaanderson** [comment]
:rip:

**Comment by aaaanderson** [comment]
admin abuse

**Comment by rob0rt** [comment]
:rip:

**Comment by arrdem** [comment]
I JUST ENJOY WATCHING LANBOT KILLSTREAK @aetherson OKAY

**Comment by aaaanderson** [comment]
just like 1.5ks from bolivia killstreak you

**Pull request closed without merging**
