### PR TITLE
change :yeezus: response on "Kanye" to :yee:

### PR DESCRIPTION
**Pull request by Chigg**
this small change will provide for a 50% conservation in characters

### CODE REVIEW

**Comment by rob0rt** [comment]
:shipit:

**Comment by jthaden** [comment]
:shipit:

**Comment by Chigg** [comment]
http://i.imgur.com/IkhY5vb.jpg

**Comment by arrdem** [comment]
U DON'T FUKKKN OWN ME

**Comment by rob0rt** [comment]
R
E
K
T

**Comment by Chigg** [comment]
why I never

**Pull request closed without merging**
