### PR TITLE
Added response muting

### PR DESCRIPTION
**Pull request by ThomasGaubert**
`lanbot stfu`

### CODE REVIEW

**Comment by arrdem** [comment]
yaaaaaaaay

**Comment by stevendiaz** [comment]
nice play

**Comment by dwetterau** [comment]
o.0 

For future reference, if you notice yourself adding the same conditional a bunch of times, (aka you're copy pasting) then you're probably not doing writing your code in the cleanest or most maintainable manner.

One thing you might consider to clean this up in the future would be to define a `send` function that you pass `msg` into and then check if it's muted or not. This would greatly simplify what would need to be updated if you ever wanted to add more to that conditional (e.g. `!responses.isMuted(msg) and not isDay(SATURDAY)`).

Just food for thought. :)

**Comment by ThomasGaubert** [comment]
Yeah I did this fairly late, I'll be cleaning it up soon. Thanks though!

**Pull request merged**
