### PR TITLE
Remove that trash plugin

### PR DESCRIPTION
**Pull request by rob0rt**

### CODE REVIEW

**Comment by aaaanderson** [comment]
lanbot markov robert sucks

**Comment by rob0rt** [comment]
This plugin is awful and you know it

**Comment by aaaanderson** [comment]
best plugin, learns Marx more readily than anyone else in LAN

**Comment by arrdem** [comment]
So I'm not gonna merge this one yet. The shit that you've collectively fed into lanbot is honestly pretty revolting and no I'm not just talking about Marx. Lanbot has never meaningfully contributed with a markov statement and since most of the markov training seems to be copypasta rather than logs I'm inclined to just remove the plugin in the face of continued and rather revolting abuse.

**Comment by rob0rt** [comment]
That's why I put it up to get rid of it. It's honestly only served to be a point of abuse.

**Comment by dwetterau** [comment]
> So I'm not gonna merge this one yet.
> arrdem merged commit 6977535
> :+1:

**Pull request merged**
