### PR TITLE
Replace hubot-plusplus

### PR DESCRIPTION
**Pull request by ThomasGaubert**
Replace hubot-plusplus with [hubot-plusplus-plus](https://github.com/ThomasGaubert/hubot-plusplus-plus). Annoying users and reasons are no longer allowed.

This is why we can't have nice things.

### CODE REVIEW

**Comment by arrdem** [comment]
merge conflicts?

**Comment by ThomasGaubert** [comment]
Whoops, fixed.

**Comment by arrdem** [comment]
son I need to teach you how to rebase

**Comment by ThomasGaubert** [comment]
arrsorry :cry:

**Comment by arrdem** [comment]
just run this:

```
$ git reset --hard a32b56f
$ git rebase upstream/master
$ git push -f
```

**Comment by rob0rt** [comment]
`--hard`

Solid life advice from the arrdmin

**Comment by ThomasGaubert** [comment]
:shipit:

**Comment by arrdem** [comment]
the youngling has rebased

I am proud

**Pull request merged**
