### PR TITLE
Remove :hankey: code

### PR DESCRIPTION
**Pull request by rob0rt**

### CODE REVIEW

**Comment by arrdem** [comment]
l m a o

**Comment by gregorycerna** [comment]
🔥

**Comment by coltwhaley** [comment]
Not only did he push his own PR through, it's not even correct. He calls `:yeezus:` on a Kendrick lyric...

**Comment by rainiera** [comment]
#78 does this too, and I think a revert by the original author is cleaner than a patch. At least that's my intuition...

**Comment by arrdem** [comment]
preemptively removed @rainiera 's merge auth

**Comment by rob0rt** [comment]
Good call

**Comment by rob0rt** [comment]
Not hasn't spoken about this one.
Besides, it shouldn't be in here anyways

**Comment by arrdem** [comment]
arbitrary maintainership is arbitrary

**Comment by rob0rt** [comment]
:tada:

**Pull request merged**
