### PR TITLE
Congratulations, you won!

### PR DESCRIPTION
**Pull request by rob0rt**

### CODE REVIEW

**Comment by aaaanderson** [comment]
MERGE THIS PRONTO

**Comment by arrdem** [comment]
Please refactor to remove the possibility of the bot double posting and exploding into a clout of nasal daemons.

**Comment by aaaanderson** [comment]
actually that's the actual prize

**Comment by rob0rt** [comment]
Happy @arrdem

**Comment by aaaanderson** [comment]
september 2 is arrdem day

happy arrdem to you too

**Comment by rob0rt** [comment]
:tada:

**Comment by arrdem** [comment]
Not what I had in mind but it'll do.

**Pull request merged**
