### PR TITLE
end the pain

### PR DESCRIPTION
**Pull request by aaaanderson**

### CODE REVIEW

**Comment by arrdem** [comment]
How the fuck did you get that big merge commit.

**Comment by aaaanderson** [comment]
i didnt want to do things properly so i used the web interface for everything

**Comment by arrdem** [comment]
Rebase please.

**Comment by gregorycerna** [comment]
He didn't rebase his fork onto the latest commit

**Comment by aaaanderson** [comment]
you've merged shittier code reid

**Comment by arrdem** [comment]
No I actually haven't.

**Pull request closed without merging**
